language: python
python:
 - 2.7
 - 3.6
install:
 - pip install tox
script:
 - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then tox -e py27; fi
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then tox -e py36; fi
